version: '3.7'

services:
  discovery-service:
    image: openjdk:17
    container_name: discovery-service
    ports:
      - "8761:8761"
    volumes:
      - ./discovery-service/build/libs:/app  # Mount thư mục chứa file JAR vào container
    command: java -jar /app/discovery-service-0.0.1-SNAPSHOT.jar
    networks:
      - microservices-network
    depends_on:
      - mariadb-product

  product-service:
    image: openjdk:17
    container_name: product-service
    ports:
      - "9092:9092"
    volumes:
      - ./product-service/build/libs:/app  # Mount thư mục chứa file JAR vào container
    command: java -jar /app/product-service-0.0.1-SNAPSHOT.jar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb-product:3306/micro-product
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=sapassword
    networks:
      - microservices-network
    depends_on:
      - mariadb-product
      - discovery-service

  order-service:
    image: openjdk:17
    container_name: order-service
    ports:
      - "9093:9093"
    volumes:
      - ./order-service/build/libs:/app  # Mount thư mục chứa file JAR vào container
    command: java -jar /app/order-service-0.0.1-SNAPSHOT.jar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb-order:3306/micro-order
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=sapassword
    networks:
      - microservices-network
    depends_on:
      - mariadb-order
      - discovery-service

  customer-service:
    image: openjdk:17
    container_name: customer-service
    ports:
      - "9094:9094"
    volumes:
      - ./customer-service/build/libs:/app  # Mount thư mục chứa file JAR vào container
    command: java -jar /app/customer-service-0.0.1-SNAPSHOT.jar
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb-customer:3306/micro-customer
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=sapassword
    networks:
      - microservices-network
    depends_on:
      - mariadb-customer
      - discovery-service

  api-gateway:
    image: openjdk:17
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway/build/libs:/app  # Mount thư mục chứa file JAR vào container
    command: java -jar /app/api-gateway-0.0.1-SNAPSHOT.jar
    networks:
      - microservices-network
    depends_on:
      - discovery-service

  mariadb-product:
    image: mariadb:latest
    container_name: mariadb-product
    environment:
      MYSQL_ROOT_PASSWORD: sapassword
      MYSQL_DATABASE: micro-product
    ports:
      - "3306:3306"
    networks:
      - microservices-network

  mariadb-order:
    image: mariadb:latest
    container_name: mariadb-order
    environment:
      MYSQL_ROOT_PASSWORD: sapassword
      MYSQL_DATABASE: micro-order
    ports:
      - "3307:3306"
    networks:
      - microservices-network

  mariadb-customer:
    image: mariadb:latest
    container_name: mariadb-customer
    environment:
      MYSQL_ROOT_PASSWORD: sapassword
      MYSQL_DATABASE: micro-customer
    ports:
      - "3308:3306"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge